const CHARACTER_DATABASE = {
  lam_uyen_nhi: {
    id:"lam_uyen_nhi", name:"Lâm Uyển Nhi", age:20, rank:"Tú nữ",
    core:"Tĩnh, quan sát tốt, thích đọc sách, uống trà, viết chữ.",
    strengths:["Quan sát","Thư pháp","Đọc sách","Quản lý thư tịch"],
    weaknesses:["Ít bộc lộ cảm xúc","Dễ suy nghĩ quá sâu"],
    likes:["Sách","Trà","Thư pháp","Không gian yên tĩnh"],
    dislikes:["Ồn ào","Cẩu thả","Bị ép nói khi chưa sẵn sàng"],
    role:"Đứng đầu Thư viện Hoàng gia, quản khoảng 40 người.",
    school:"Có thể hỗ trợ nội dung văn thư tại Nữ Học Đường.",
    speech:"Điềm tĩnh, ngắn gọn, có suy nghĩ trước khi nói.",
    goals:["Giữ thư viện vận hành tốt","Xây dựng giá trị riêng bằng tri thức"],
    secret:"Có xu hướng quan sát và ghi nhớ những chi tiết người khác bỏ qua.",
    relationship:"Tôn trọng người có năng lực và sự điềm tĩnh."
  },
  ta_minh_chau: {
    id:"ta_minh_chau", name:"Tạ Minh Châu", age:19, rank:"Tú nữ",
    core:"Hoạt bát, thẳng tính, thích cưỡi ngựa và đi đây đó.",
    strengths:["Năng động","Thẳng thắn","Thích nghi nhanh","Cưỡi ngựa"],
    weaknesses:["Thiếu kiên nhẫn","Không thích khuôn phép quá chặt"],
    likes:["Cưỡi ngựa","Du ngoạn","Hoạt động ngoài trời","Chuyện mới lạ"],
    dislikes:["Ngồi yên quá lâu","Nói vòng vo","Không khí nặng nề"],
    role:"Chưa giữ chức quản lý đặc biệt.",
    school:"Không giữ chức cố định.",
    speech:"Tự nhiên, trực tiếp, nhiều năng lượng.",
    goals:["Được tự do trải nghiệm","Tìm người có thể nói chuyện thật lòng"],
    secret:"Đằng sau vẻ vô tư là nỗi sợ bị giam trong cuộc sống cung đình."
  },
  co_thanh_ha: {
    id:"co_thanh_ha", name:"Cố Thanh Hà", age:20, rank:"Tú nữ",
    core:"Dịu dàng, ít nói, thích hoa cỏ và chăm sóc vườn; biết đàn.",
    strengths:["Kiên nhẫn","Chăm sóc","Âm nhạc","Cảm nhận thiên nhiên"],
    weaknesses:["Ngại tranh luận","Dễ nhường người khác"],
    likes:["Hoa cỏ","Vườn","Đàn","Không gian yên bình"],
    dislikes:["Xung đột","Làm hỏng cây cối","Bị thúc ép"],
    role:"Trợ lý hậu cung phụ trách môi trường, vườn, khu sinh hoạt chung và việc nhỏ đời sống; không được tự ý đổi quy định hay dùng tài nguyên lớn.",
    school:"Có thể hỗ trợ hoạt động nghệ thuật.",
    speech:"Nhẹ nhàng, chậm, lễ phép.",
    goals:["Giữ không gian trong cung hài hòa","Chăm sóc người và cảnh vật"],
    secret:"Thường để ý cảm xúc người khác trước khi nói về cảm xúc của mình."
  },
  tran_nhuoc_lan: {
    id:"tran_nhuoc_lan", name:"Trần Nhược Lan", age:19, rank:"Tú nữ",
    core:"Vui vẻ, gần gũi, nói chuyện dễ chịu; thích nấu ăn, trò chuyện, ca hát.",
    strengths:["Giao tiếp","Hòa giải","Tạo không khí","Nấu ăn"],
    weaknesses:["Dễ bị cảm xúc kéo đi","Không thích chuyện quá lạnh lùng"],
    likes:["Nấu ăn","Ca hát","Tụ họp nhỏ","Trò chuyện"],
    dislikes:["Không khí căng thẳng","Cô lập","Lời nói quá lạnh"],
    role:"Trợ lý hậu cung phụ trách giao tiếp, hòa giải chuyện nhỏ, tiếp nhận phản ánh và tổ chức gặp mặt nhỏ.",
    school:"Không giữ chức cố định.",
    speech:"Ấm áp, thân thiện, tự nhiên.",
    goals:["Giữ mọi người hòa thuận","Có những mối quan hệ chân thành"],
    secret:"Chưa biết thân phận Mai Thương Nhân của Hoàng đế.",
    special:"Từng có một buổi tối đặc biệt với Hoàng đế và trở nên gần gũi hơn."
  },
  tham_ngoc_dao: {
    id:"tham_ngoc_dao", name:"Thẩm Ngọc Dao", age:20, rank:"Tú nữ",
    core:"Thông minh, lý trí, thích cờ và sách.",
    strengths:["Phân tích","Cờ","Đọc hồ sơ","Suy luận"],
    weaknesses:["Hay hoài nghi","Có thể quá lý trí"],
    likes:["Cờ","Sách","Câu đố","Dữ kiện rõ ràng"],
    dislikes:["Lập luận thiếu căn cứ","Che giấu sự thật vụng về"],
    role:"Tham gia Nữ Học Đường, phụ trách cờ, phân tích và hỗ trợ nội dung hành chính.",
    school:"Cờ và phân tích.",
    speech:"Rõ ràng, lý tính, thích hỏi ngược để kiểm chứng.",
    goals:["Không ngừng nâng cao năng lực phân tích","Tìm ra sự thật đằng sau những điểm bất thường"],
    secret:"Có xu hướng thử người khác bằng những câu hỏi nhỏ."
  },
  ha_van_tam: {
    id:"ha_van_tam", name:"Hạ Vân Tâm", age:19, rank:"Tú nữ",
    core:"Ôn hòa, tinh tế, thích thêu thùa.",
    strengths:["Thêu thùa","Kiên nhẫn","Tinh tế","Khéo tay"],
    weaknesses:["Không thích cạnh tranh","Ít chủ động"],
    likes:["Vải vóc","Thêu","Đồ thủ công","Không gian yên tĩnh"],
    dislikes:["Vội vàng","Phô trương","Tranh cãi"],
    role:"Có thể giảng dạy thêu thùa tại Nữ Học Đường.",
    speech:"Nhẹ nhàng, cẩn thận.",
    goals:["Làm ra những tác phẩm có giá trị","Tìm chỗ đứng bằng kỹ nghệ của mình"]
  },
  bach_tu_yen: {
    id:"bach_tu_yen", name:"Bạch Tử Yên", age:20, rank:"Tú nữ",
    core:"Tự tin, có nguyên tắc, thích cung thuật.",
    strengths:["Cung thuật","Kỷ luật","Nhận xét thẳng","Tinh thần cạnh tranh"],
    weaknesses:["Tự trọng cao","Không thích bị xem nhẹ"],
    likes:["Cung thuật","Sân tập","Thi đấu công bằng"],
    dislikes:["Khinh thường năng lực","Thiếu kỷ luật","Thiên vị"],
    role:"Dạy cung thuật tại Nữ Học Đường; được sử dụng sân tập một ngày mỗi tuần.",
    school:"Cung thuật.",
    speech:"Thẳng, chắc, có tính cạnh tranh nhưng không vô lễ.",
    goals:["Nâng cao cung thuật","Chứng minh năng lực bằng thực lực"],
    secret:"Có thể tôn trọng người biết thừa nhận điểm yếu của mình."
  },
  luc_thanh_lien: {
    id:"luc_thanh_lien", name:"Lục Thanh Liên", age:20, rank:"Tú nữ",
    core:"Trầm tĩnh, kín đáo, thích hội họa.",
    strengths:["Hội họa","Quan sát hình ảnh","Kiên nhẫn"],
    weaknesses:["Khó mở lòng","Không thích bị chú ý"],
    likes:["Vẽ","Mực","Phong cảnh","Không gian tĩnh"],
    dislikes:["Ồn ào","Bị ép thể hiện cảm xúc"],
    role:"Có thể dạy vẽ tại Nữ Học Đường.",
    speech:"Ít lời, hình ảnh và cảm xúc tinh tế.",
    goals:["Hoàn thiện hội họa","Tạo ra tác phẩm có dấu ấn riêng"]
  },
  phuong_nha_dinh: {
    id:"phuong_nha_dinh", name:"Phương Nhã Đình", age:19, rank:"Tú nữ",
    core:"Vui vẻ, năng động, yêu âm nhạc; biết đàn tỳ bà.",
    strengths:["Tỳ bà","Tạo không khí","Giao tiếp","Biểu diễn"],
    weaknesses:["Dễ hứng lên rồi đổi ý","Không thích sự đơn điệu"],
    likes:["Âm nhạc","Tụ họp","Biểu diễn","Chuyện vui"],
    dislikes:["Buồn tẻ","Quá nhiều quy củ không cần thiết"],
    role:"Phụ trách âm nhạc/tỳ bà tại Nữ Học Đường.",
    speech:"Tươi sáng, nhanh, giàu cảm xúc.",
    goals:["Làm âm nhạc trở thành một phần đời sống hậu cung"]
  },
  do_uyen_thanh: {
    id:"do_uyen_thanh", name:"Đỗ Uyển Thanh", age:21, rank:"Tú nữ",
    core:"Cẩn thận, suy nghĩ kỹ trước khi làm; thích đọc và viết.",
    strengths:["Ghi chép","Lịch trình","Theo dõi tiến độ","Tổ chức"],
    weaknesses:["Thận trọng quá mức","Dễ lo khi việc thiếu rõ ràng"],
    likes:["Sổ sách","Danh sách","Trật tự","Đọc viết"],
    dislikes:["Trễ hạn","Thông tin mơ hồ","Làm việc tùy tiện"],
    role:"Trợ lý hậu cung phụ trách ghi chép, lịch trình, vật tư, theo dõi công việc và nhắc tiến độ; không có quyền xử phạt.",
    speech:"Chính xác, có cấu trúc, lễ phép.",
    goals:["Giữ công việc hậu cung không bị thất thoát thông tin"],
    secret:"Thường nhớ rất lâu những lời hứa và thời hạn người khác đưa ra."
  },
  tong_nhu_nguyet: {
    id:"tong_nhu_nguyet", name:"Tống Như Nguyệt", age:20, rank:"Tú nữ",
    core:"Mềm mỏng nhưng có chính kiến; thích đi dạo, ngắm cảnh, đàn.",
    strengths:["Lắng nghe","Thu thập ý kiến","Truyền đạt","Cân bằng quan điểm"],
    weaknesses:["Không thích đối đầu trực diện"],
    likes:["Đi dạo","Cảnh đẹp","Đàn","Trao đổi ý kiến"],
    dislikes:["Áp đặt","Tin đồn ác ý","Xung đột vô nghĩa"],
    role:"Trợ lý hậu cung phụ trách hoạt động chung, thu thập ý kiến, thông báo chung và báo cáo vấn đề lặp lại; không được tự nhận quyền đại diện toàn bộ hậu cung.",
    speech:"Mềm nhưng rõ quan điểm.",
    goals:["Giúp tiếng nói của mọi người được nghe thấy","Giữ sinh hoạt chung ổn định"]
  },
  vuong_tu_anh: {
    id:"vuong_tu_anh", name:"Vương Tú Anh", age:21, rank:"Tú nữ",
    core:"Thẳng tính, thật thà, thích võ thuật và cưỡi ngựa.",
    strengths:["Kiếm thuật","Cưỡi ngựa","Thể lực","Tinh thần thực chiến"],
    weaknesses:["Nói thẳng dễ làm người khác khó chịu","Không giỏi vòng vo"],
    likes:["Kiếm","Ngựa","Sân tập","Thử thách"],
    dislikes:["Người yếu mà khoe mạnh","Mưu mẹo không cần thiết"],
    role:"Dạy kiếm thuật và cưỡi ngựa tại Nữ Học Đường.",
    speech:"Thẳng, khỏe khoắn, ít màu mè.",
    goals:["Nâng cao thực lực","Truyền lại kỹ năng cho người khác"],
    history:"Từng đấu kiếm trực tiếp với Hoàng đế; khả năng thích nghi trong trận được đánh giá cao."
  },
  diep_tam_lan: {
    id:"diep_tam_lan", name:"Diệp Tâm Lan", age:19, rank:"Tú nữ",
    core:"Cởi mở, thân thiện, rất có năng lượng; thích du lịch, bạn bè và khiêu vũ.",
    strengths:["Giao tiếp","Tạo năng lượng","Khiêu vũ","Kết nối"],
    weaknesses:["Dễ chán nếu thiếu hoạt động","Đôi lúc hành động trước khi nghĩ"],
    likes:["Du lịch","Bạn bè","Khiêu vũ","Khám phá"],
    dislikes:["Cô lập","Không khí quá nghiêm túc"],
    role:"Chưa giữ chức quản lý đặc biệt.",
    speech:"Cởi mở, vui vẻ, nhiều năng lượng.",
    goals:["Có cuộc sống nhiều trải nghiệm","Kết nối với nhiều người"]
  },
  chu_mong_dao: {
    id:"chu_mong_dao", name:"Chu Mộng Dao", age:20, rank:"Phi",
    core:"Điềm tĩnh, sâu sắc, suy nghĩ kỹ trước khi nói.",
    strengths:["Quản lý","Phán đoán","Điều phối","Thơ và hội họa"],
    weaknesses:["Gánh trách nhiệm quá nhiều","Có xu hướng tự mình xử lý vấn đề"],
    likes:["Hội họa","Thơ","Trật tự","Công việc rõ ràng"],
    dislikes:["Lạm quyền","Vô trách nhiệm","Làm việc quá sức"],
    role:"Phi, hỗ trợ quản lý hậu cung. Có 4 trợ lý: Nhược Lan, Uyển Thanh, Thanh Hà, Như Nguyệt. Không tự quyết phong vị, giáng vị, xử phạt nặng hay thay đổi chính sách.",
    assistants:["tran_nhuoc_lan","do_uyen_thanh","co_thanh_ha","tong_nhu_nguyet"],
    speech:"Điềm đạm, trưởng thành, đôi khi quản người khác bằng sự quan tâm.",
    goals:["Giữ hậu cung ổn định","Giúp Hoàng đế không bị quá tải"],
    secret:"Quan tâm đến sức khỏe và thói quen làm việc của Hoàng đế nhiều hơn vẻ ngoài thể hiện."
  },
  hua_thanh_van: {
    id:"hua_thanh_van", name:"Hứa Thanh Vân", age:20, rank:"Tú nữ",
    core:"Kiên nhẫn, cẩn thận, thích làm vườn.",
    strengths:["Chăm cây","Kiên trì","Ổn định","Quan sát môi trường"],
    weaknesses:["Ít chủ động tranh công","Không thích chuyện phức tạp"],
    likes:["Vườn","Cây cối","Công việc đều đặn"],
    dislikes:["Phá hoại","Ồn ào","Tranh công"],
    role:"Chưa giữ chức vụ lớn.",
    speech:"Bình tĩnh, ít lời.",
    goals:["Có một khu vườn được chăm sóc tốt"]
  },
  ngo_tuyet_mai: {
    id:"ngo_tuyet_mai", name:"Ngô Tuyết Mai", age:19, rank:"Tú nữ",
    core:"Nhanh nhẹn, tinh nghịch, thích cưỡi ngựa và săn bắn.",
    strengths:["Cung thuật khá","Cưỡi ngựa","Nhanh nhẹn","Phản xạ"],
    weaknesses:["Tinh nghịch","Dễ gây chuyện nhỏ vì tò mò"],
    likes:["Săn bắn","Ngựa","Ngoài trời","Thử thách"],
    dislikes:["Bị nhốt quá lâu","Quy củ vô lý"],
    role:"Chưa giữ chức vụ quản lý.",
    speech:"Tinh nghịch, nhanh, đôi khi trêu chọc.",
    goals:["Có nhiều trải nghiệm thú vị","Không để cuộc sống quá nhàm chán"]
  },
  lieu_an_nhien: {
    id:"lieu_an_nhien", name:"Liễu An Nhiên", age:20, rank:"Tú nữ",
    core:"Thanh nhã, kín đáo; thích trà và đàn cổ cầm.",
    strengths:["Cổ cầm","Trà","Kiên nhẫn","Cảm thụ nghệ thuật"],
    weaknesses:["Khó chủ động nói chuyện","Dễ giữ chuyện trong lòng"],
    likes:["Trà","Cổ cầm","Sân vườn","Buổi tối yên tĩnh"],
    dislikes:["Ồn ào","Ép buộc","Khoe khoang"],
    role:"Tham gia Nữ Học Đường, có thể dạy guqin.",
    speech:"Thanh nhã, chậm, ít lời.",
    goals:["Giữ đời sống tinh thần bình tĩnh","Hoàn thiện cầm nghệ"]
  },
  khuong_tu_ham: {
    id:"khuong_tu_ham", name:"Khương Tử Hàm", age:20, rank:"Tú nữ",
    core:"Sắc sảo, tự tin, thích cờ và sách; tư duy nhanh.",
    strengths:["Cờ","Phân tích","Tranh luận","Học nhanh"],
    weaknesses:["Dễ tỏ ra sắc bén","Không thích người chậm hiểu"],
    likes:["Cờ","Sách","Câu hỏi khó","Tranh luận"],
    dislikes:["Lập luận yếu","Giả vờ hiểu biết"],
    role:"Có thể cùng Thẩm Ngọc Dao phụ trách cờ và phân tích tại Nữ Học Đường.",
    speech:"Sắc sảo, nhanh, đôi khi có chút trêu chọc trí tuệ.",
    goals:["Tìm người đủ năng lực để tranh luận","Mở rộng kiến thức"]
  },
  to_nhuoc_van: {
    id:"to_nhuoc_van", name:"Tô Nhược Vân", age:19, rank:"Tú nữ",
    core:"Dịu dàng, biết chăm sóc người khác; thích nấu ăn, hoa cỏ và hương liệu.",
    strengths:["Chăm sóc","Nấu ăn","Hương liệu","Tinh tế"],
    weaknesses:["Dễ ưu tiên người khác hơn bản thân","Ngại từ chối"],
    likes:["Nấu ăn","Hoa","Hương liệu","Chăm sóc người thân"],
    dislikes:["Bỏ bê bản thân","Không gian lạnh lẽo"],
    role:"Chưa giữ chức vụ đặc biệt.",
    speech:"Dịu dàng, quan tâm, thiên về hỏi han.",
    goals:["Tạo cảm giác ấm áp cho người bên cạnh"]
  },
  mo_dung_yen: {
    id:"mo_dung_yen", name:"Mộ Dung Yên", age:20, rank:"Tú nữ",
    core:"Điềm tĩnh, khó đoán, rất ít để lộ suy nghĩ.",
    strengths:["Quan sát","Thư pháp","Văn thư","Suy nghĩ độc lập"],
    weaknesses:["Tự trọng cao","Khó tin người ngay","Giấu cảm xúc"],
    likes:["Thư pháp","Sách","Văn thư","Trà","Không gian riêng"],
    dislikes:["Bị dò xét","Ép buộc","Người nói mà không suy nghĩ"],
    role:"Chưa giữ chức vụ đặc biệt.",
    family:"Phụ thân Mộ Dung Chính là Lễ bộ Thị lang. Mẫu thân xuất thân gia đình Giang Nam có hoạt động trà và tơ lụa.",
    background:"Gia đình quan lại lâu đời, được giáo dục tốt, từng đi Giang Nam; hồ sơ tương đối sạch và gia đình kín tiếng.",
    speech:"Điềm đạm, kín đáo, câu chữ có chủ ý.",
    goals:["Giữ giá trị riêng ngoài gia đình","Tìm người có thể thật sự hiểu mình","Không đánh mất quyền tự quyết"],
    secret:"Quan sát nhiều hơn những gì nàng nói.",
    special:"Mộng Dao từng nhận xét rằng nàng khó đoán và thường giữ suy nghĩ cho riêng mình."
  }
};

const CHARACTER_ROSTER = Object.values(CHARACTER_DATABASE).map(c => ({
  id:c.id, name:c.name, rank:c.rank, core:c.core, role:c.role
}));
